dane section testimonials kust need correct text
StingStorm/project-nineGreatWaysToCode pull request #1
Opened 2024-05-24 23:53 UTC by AlinaWhite

потрібно поправити інтервал тексту в формах

2024-05-25 02:11 UTC, StingStorm requested changes

2024-05-25 02:11 UTC, StingStorm commented on src/partials/testimonials.html
> +<section class="revius-block container section-padding">
Не може бути елемент одночасно і контейнером і секцією. Контейнер у нас обмежен по ширині, центрован та має горизонтальні паддінги. Секція має бути на всю ширину боді та мати вертикальні паддінги, якщо іншого не заначено в макеті.  Огорніть контент всередині секції у дів, та вкажіть йому класс `container`

![image](https://github.com/StingStorm/project-nineGreatWaysToCode/assets/57044358/645f189b-b089-400b-a01f-ae047c0fd5ce)

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +    color: var(--primary-text-hex);
цей код зайвий. Заголовок успадковує колір від body

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +    padding-top: 54px;
На мій погляд логічніше вказати верхній паддінг для самої картки, ніж розтягувати блок заголовку

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +    transform: translateX(-32px);
зазвичай комбінація центрування виглядає так:
`left: 50%;
transform: translateX(-50%)`;

Вийде те саме але не доведеться рахувати половину від ширини зображення, та такий варіант біль адаптивний. Підлаштується під будь-які розміри зображення

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +    color: rgba(252, 249, 249, 0.4);
`font-size: 400`?
`font-weight: 400` - зазвичай не вказують без потреби так як це значення за замовченням для елементів які не є заголовоками

2024-05-25 02:11 UTC, StingStorm commented on src/partials/testimonials.html
> +        </div>
В середенні тегу `<ul>` не може бути тегів окрім `<li>`. В самих лішках вже може бути все що завгодно
Нажаль такий код не пройде валідатор через вкладенні у ul діви

![image](https://github.com/StingStorm/project-nineGreatWaysToCode/assets/57044358/31beb3d4-346f-495d-b837-9c0d47ee7ee0)

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +        height: 243px;
Зазвичай висоту не вказуємо бо елементи мають самостійно розтягувати контейнер за рахунок падінгів та контенту. Але якщо ідея у тому що ми хочемо зробити фіксованну мінмальну висоту картки на випадок якщо тексту буде замало - тоді логінчіше вказати саме `min-height;`. Тоді картка буде розтягуватись якщо тексту буде більше інакше текст буде вилазити за межі картки

2024-05-25 02:11 UTC, StingStorm commented on src/css/testimonials.css
> +        column-gap: 26px;
Ми також робимо брекпоінт для 1440px. Зверніть увагу що там розміри карток трохи більше ніж у десктопі. Можливо є сенс використати `calc((100% - gap) / quantity)`

2024-05-26 16:43 UTC, StingStorm requested changes

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +    padding-bottom: 150px;
з погляду на те що в тебе паддінг відрізняється він глобального стилю, то логічніше не під'єднувати глобальний стил взагалі. Просто вкажи верхній паддінг для цього класу. А клас section-padding прибери з розмітки

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +    position: relative;
там на мобілці горизонтальні паддінги по 22px. Вкажи їх окремо через падінг лефт/райт у медіа запиті для мобілки через max-width: 767px

2024-05-26 16:43 UTC, StingStorm commented on src/partials/testimonials.html
> +        <li class="revius-item revius-hide-phone revius-hide-ipad">
В цілому твоє рішення з додатковими класами теж вірне. Але можна було б просто в медіа запитах вказати `revius-item:nth-child(3)`. Але то таке, перероблювати не обв'язково. Обидва варіанти норм

+ На майбутнє скажу що такі елементи скоріш за все є слайдерами то му елементи на брейк поінтах не ховаються через дісплей: нан, а розташовуються за мажеми списку через оверфлоу хідден. Типу вони є, але їх не видно за межами контейнеру
Но зараз я пока що не буду реалізовувати тут слайдер, бо доведеться махатись з зображеннями, їх буде обрізати. Якщо залишиться час - спробуємо

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +    position: relative;
Також додам що на мій погляд всеж таки треба обмежити висоту карток через `min-height:` тому що судячи з макету розміри зовсім трошки але відрізняються і ми бачимо що відступи від тексту до контейнеру на картках відрізняються в залежності від кілкості самого тексту але при цьому у самих карток розміри фіксованні. 

Тому бажано все ж додати цю властивість з адаптуванням під брейкпоінти

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +        font-size: 14px;
на мобілці нема сенсу вказувати цей розмір шрифту, бо текст успадкує його від боді

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +        font-size: 16px;
Нема сенсу закривати цю властивість у планшеті щоб потім її знов вказувати у десктопах. Ти можешь вкладати медіа запити один до одного.

```
@media screen and (min-width: 768px)  {

    .revius-text {
        font-size: 16px;
 }
  @media screen and (max-width: 1279px) {
    .revius-hide-ipad {
        display: none;
    }

    .revius-list {
        column-gap: 32px;
    }
}
}
```

таким чином розмір тексту буде спрацьовувати при  (min-width: 768px)
а дісплей та колумн геп при  (min-width: 768px) and (max-width: 1279px) 
Зверни увагу що я саме вклав другий медіа запит у перший, а не написав їх один під одним

2024-05-26 16:43 UTC, StingStorm commented on src/css/testimonials.css
> +        font-size: 16px;
якщо використати вкладені медіа запити з комментару вище - це правило можна прибрати

2024-05-26 21:11 UTC, AlinaWhite commented on src/css/testimonials.css
> +    position: relative;
дивно що в inspect styles падінки показує 0 18 18 18 як і в інших а яущо самому міряти 22
виправила на 22

2024-05-27 01:05 UTC, StingStorm approved these changes

2024-05-27 01:05 UTC, merged