About us
StingStorm/project-nineGreatWaysToCode pull request #2
Opened 2024-05-25 12:34 UTC by Daryna010203

2024-05-25 12:50 UTC, Daryna010203 commented
Буду рада всім настановам та чекаю перевірки)

2024-05-25 19:57 UTC, StingStorm requested changes

2024-05-25 19:57 UTC, StingStorm commented on src/css/about-us.css
> +  margin-bottom: 40px;
Загальні класи можна лише додавати у html для того щоб використати їх стилі та не дублювати код. Додатакові стилі можна вказувати лише для нових класів. Цей стиль буде впливати на всі заголовки з цим класом у всіх секціях. Десь це може заважати. 
Правило залиште але змініть класс на свій. Наприклад `.section-about-title`

2024-05-25 19:57 UTC, StingStorm commented on src/css/about-us.css
> +}
зверни увагу що у зображення мають бути заокруглені кути.
Необхідно додати border-radius та overflow для діва-обгортки

Також перевір будь ласка чи потрібні тобі ці роміри на всіх брейкпоінтах, бо на мій погляд не потрібні. Зображення самі встають по доступній ширіні. Тільки коли будешь перевиряти - прибирай одразу всі, бо можешь ввести себе в оману якщо наприклад через видалення ширини на таблетці буду спрацьвувати розміри мобільні

2024-05-25 19:57 UTC, StingStorm commented on src/css/about-us.css
> +
не дуже зрозумів для чого ці властивості

2024-05-25 19:57 UTC, StingStorm commented on src/css/about-us.css
> +    margin: 0;
Доволі цікава реалізація. Я мабуть обмежував би за розміром саме параграфи та робив би геп між текстовим контейнером там зображенням. В цілому обидва варіанти норм за єдиною різницєю геп тут виглядає трохи краще ніж паддінг. Але норм. Вважаю що можна залишити твій варіант 

єдине що точно не дуже ок - це скидання маржинів в 0 на брейк поінтах. Краще закрити стилі для нижніх маржинів для таблетки та мобілки в медіа запитах через (max-width: 767/1279 px). Так вони будуть використовуватись лише на своїх брейк поінтах та не доведеться іх скидати в 0 навмисно

2024-05-25 19:57 UTC, StingStorm commented on src/partials/about-us.html
> +    <div class="about-us-description about-us-block">
другий клас наче не використовується ?

2024-05-25 20:12 UTC, StingStorm commented on src/partials/about-us.html
> +<section class="section-padding about-us-section">
Всім секціям які є якорями для навігаційних посиланнь у хедері та футері треба на секцію вказувати id="" зі значенням яке повторює літеру до літери текст посилання. з додаванням дефісу якщо слова 2 та всіма маленькими літерами

2024-05-26 17:43 UTC, Daryna010203 commented on src/css/about-us.css
> +  margin-bottom: 40px;
змінила, дякую

2024-05-26 17:44 UTC, Daryna010203 commented on src/css/about-us.css
> +}
Все підлаштувалося автоматично, зайві розміри до блоку видалила але додала розміри до тегу <source> щоб сторінка не стрибала в разі повільного інтернету.

2024-05-26 17:44 UTC, Daryna010203 commented on src/css/about-us.css
> +
чомусь вирішила додати на майбутнє, якщо буде необхідність змінити фото з невідповідними розмірами. Але вже прибрала

2024-05-26 17:44 UTC, Daryna010203 commented on src/css/about-us.css
> +    margin: 0;
виправила

2024-05-26 17:44 UTC, Daryna010203 commented on src/partials/about-us.html
> +    <div class="about-us-description about-us-block">
зайве прибрала

2024-05-26 17:44 UTC, Daryna010203 commented on src/partials/about-us.html
> +<section class="section-padding about-us-section">
якір до секції додала

2024-05-26 19:24 UTC, StingStorm approved these changes

2024-05-26 19:24 UTC, merged