add footer
StingStorm/project-nineGreatWaysToCode pull request #3
Opened 2024-05-25 13:41 UTC by Oleh-Zakharchenko

2024-05-25 13:55 UTC, Oleh-Zakharchenko commented
ок, вже бачу що верхній бордер міг через var додати

2024-05-25 21:24 UTC, StingStorm requested changes

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +  padding-bottom: 280px;
Чому вирішив використовувати флекси? наче тут легше просто відштовхувати ніжнім маржином
Чому вирішив вказувати паддінги для контейнеру? На скільки пам'ятаю фонові зображення спокійно залазят під паддінги свого контейнеру, тому наче можна вказувати паддінги саме для секції, як це зазвичай і робимо

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +  gap: 25px;
властивість гєп задає відсутипи по всім напрямам. Тому в тебе наче трохи відрізняються відступи від макету
Слід використовувати `row-gap`

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +  order: 3;
На мій погляд простіше було використати флекс врап у парі з властивістю flex-direction: column;
Пама'ятаю що сам запропонував але після перегляду макету нормально прийшов до такого висновку. не встиг поправити тебе на зідзвоні, бо пам'ятаю що ти почав щось про "потрібно буде два контейнери" але вони не потрібні, при вертикальній геомертрії нижні врапнуться у наступну колонку

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +  transition: color var(--primary-transition);
для чого вайт спейс? наче текст в тебе не врапається у посиланнь? чи це типу перестраховка?

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +    flex-wrap: nowrap;
flex-wrap: nowrap; це властивість за замовчуванням. Якщо на нижніх точках перелому є властивості які доведеться навмисно скидати до дефолтних значень - краще закривати такі властивості у медізапитах для тих самих брейкпоінтів через `max-width` або `min-width and max-width`

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +  }
Весь код вишче зайвий. З тієї ж причини що й у попередньому комментарі

2024-05-25 21:24 UTC, StingStorm commented on src/css/footer.css
> +    width: 730px;
В тебе наче не в тому місці врапається текст та збільшується висота секції через ширину тексту. За макетом наче 754 px. 
Через цю зміну доведеться перецентровувати фон. Я на око підгнав. Замість `calc(50% - 14px);` вкажешь  `calc(50% - 14px);`

2024-05-25 21:24 UTC, StingStorm commented on src/partials/footer.html
> +    <div class="footer-nav-container">
це в нас навігація сайту. Бажанно використовувати тег `nav`

2024-05-25 21:24 UTC, StingStorm commented on src/partials/footer.html
> +        <li class="footer-nav-items footer-nav-items-about">
Додаткові класи для ордерів? Все більше погоджуюсь з тим що врап + колумн виглядає набагато краще

2024-05-26 00:57 UTC, Oleh-Zakharchenko commented on src/css/footer.css
> +  transition: color var(--primary-transition);
вайт спейс для мобілки на 320px, один напис з навігації починає займати 2 рядки

2024-05-26 17:35 UTC, StingStorm requested changes

2024-05-26 17:35 UTC, StingStorm commented on src/css/footer.css
> +    height: calc((100% - 25px) / 2);
нема сенсу використовувати і height для айтемів, і height для списку. Обери щось одне. На мій погляд краще прибрати висоту списку. А врапались вони в тебе бо там треба вказати 62px, а не 61. Скоріш за все через лайн хейт вони просто не вміщались у 61px десь на декілька сотих від 1px

2024-05-26 17:35 UTC, StingStorm commented on src/css/footer.css
> +    height: calc((100% - 25px) / 2);
ну і якщо залишишь властивість айтемів, то можешь вказати замість height - flex-basis. Еффект той самий але виглядає крутіше😎 І це слово height не буде різати око)

2024-05-26 17:35 UTC, StingStorm commented on src/partials/footer.html
> +    <div class="footer-slogan-container">
не дуже зрозумів для чого цей контейнер

2024-05-26 19:28 UTC, StingStorm approved these changes

2024-05-26 19:28 UTC, merged